# Exported from Render on 2025-01-25T21:55:13Z
services:
  # API Service
  - type: web
    name: healthcare-simulation-api
    runtime: python
    repo: https://github.com/IgorHWebDev/healthcare-simulation-api
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_SECRET
        sync: false
      - key: DB_NAME
        value: healthcare_db
      - key: API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
      - key: M3_OPTIMIZER_ENABLED
        value: "true"
      - key: METAL_FRAMEWORK_ENABLED
        value: "true"
      - key: METAL_DEVICE_WRITABLE
        value: "true"
      - key: METAL_COMPUTE_UNITS
        value: "all"
      - key: METAL_MEMORY_LIMIT
        value: "8G"
      - key: METAL_PRECISION
        value: "float16"
      - key: MEDICAL_LLM_MODEL
        value: healthcare-llm:latest
      - key: MEDICAL_LLM_ENDPOINT
        value: http://localhost:11434
      - key: OLLAMA_HOST
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: healthcare-llm:latest
      - key: OLLAMA_METAL_ENABLED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true

  # Background Worker for Analysis Tasks
  - type: worker
    name: healthcare-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A src.api.worker.celery worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: healthcare-redis
          property: connectionString

  # Database Service
  - type: pserv
    name: healthcare-db
    runtime: docker
    plan: standard
    region: oregon
    disk:
      name: healthcare-db-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    image:
      url: docker.io/library/postgres:15-alpine
    envVars:
      - key: POSTGRES_USER
        value: healthcare
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: healthcare_db

  # Redis Service
  - type: pserv
    name: healthcare-redis
    runtime: docker
    plan: free
    image:
      url: docker.io/library/redis:7-alpine
    envVars:
      - key: MAXMEMORY_POLICY
        value: noeviction

databases:
  - name: healthcare-db
    databaseName: healthcare_db
    user: healthcare
    plan: standard

  # Redis database configuration
  - name: healthcare-redis
    plan: starter
    ipAllowList: []

version: "1"