services:
  - type: web
    name: healthcare-simulation-api
    env: python
    region: frankfurt  # European region for better latency
    plan: free  # Start with free tier
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - healthcare-sim.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: / 