services:
  - type: web
    name: healthcare-simulation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - healthcare-simulation-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: / 