openapi: 3.1.0
info:
  title: IQHIS API for Custom GPT
  description: Quantum-Resistant Healthcare Information System API
  version: '0.1.0'
servers:
  - url: https://api.iqhis.local/v1
    description: Production server
security:
  - bearerAuth: []
  - apiKeyAuth: []

paths:
  /quantum/encrypt:
    post:
      operationId: encryptData
      summary: Encrypt healthcare data using quantum-resistant encryption
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EncryptionRequest'
      responses:
        '200':
          description: Data encrypted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EncryptionResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /quantum/health:
    get:
      operationId: getHealth
      summary: Get quantum system health status
      responses:
        '200':
          description: Health status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    EncryptionRequest:
      type: object
      properties:
        data:
          type: string
          description: Data to be encrypted (supports PHI with HIPAA compliance)
          maxLength: 10485760
        key_id:
          type: string
          pattern: ^qk_\d{4}_\d{2}_\d{2}.*$
          description: Optional key ID for encryption
      required:
        - data

    EncryptionResponse:
      type: object
      properties:
        encrypted_data:
          type: string
        key_id:
          type: string
        expiry:
          type: string
          format: date-time
        performance_metrics:
          $ref: '#/components/schemas/PerformanceMetrics'
      required:
        - encrypted_data
        - key_id
        - expiry

    PerformanceMetrics:
      type: object
      properties:
        encryption_time_ms:
          type: number
          format: float
        m3_acceleration_factor:
          type: number
          format: float
      required:
        - encryption_time_ms
        - m3_acceleration_factor

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        last_key_rotation:
          type: string
          format: date-time
        current_load:
          type: number
          format: float
          minimum: 0
          maximum: 1
        quantum_metrics:
          $ref: '#/components/schemas/QuantumMetrics'
      required:
        - status
        - last_key_rotation
        - current_load

    QuantumMetrics:
      type: object
      properties:
        key_strength:
          type: string
          enum: [optimal, acceptable, needs_rotation]
        encryption_queue_size:
          type: integer
        active_sessions:
          type: integer
      required:
        - key_strength
        - encryption_queue_size
        - active_sessions

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
      required:
        - code
        - message

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key 