global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quantum-agent'
    static_configs:
      - targets: ['quantum-agent:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'autogen-coordinator'
    static_configs:
      - targets: ['autogen-coordinator:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # alertmanager:9093

# Alert rules will be defined here
rule_files:
  # - "alert_rules.yml" 